services:
  postgres:
    image: postgres:16-alpine
    container_name: agente-compras-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=agente_compras_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agente-network

volumes:
  postgres_data:

networks:
  agente-network:
    driver: bridge