services:
  postgres:
    image: postgres:16-alpine
    container_name: agente-compras-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=agente_compras_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agente-network

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - DOCKER_ENV=true
      - AUTHENTICATION_API_KEY=teste
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/evolution_db
      - DATABASE_CLIENT_NAME=evolution_exchange
      - CACHE_REDIS_ENABLED=false
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1025062854
    networks:
      - agente-network

volumes:
  postgres_data:

networks:
  agente-network:
    driver: bridge